name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Prepare secrets
        run: npm run configure
        env:
          API_KEY: ${{ secrets.API_KEY }}
          OPEN_WEATHER_API: ${{ secrets.OPEN_WEATHER_API }}

      - name: Build
        run: npm run build

      - name: Add user
        run: |
          git config --global user.email "danil.rodionow13@gmail.com"
          git config --global user.name "Auto User"

      - name: Deploy
        run: |
          npm run deploy
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
