name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Prepare secrets
        run: npm run configure
        env:
          API_KEY: ${{ secrets.API_KEY }}
          OPEN_WEATHER_API: ${{ secrets.OPEN_WEATHER_API }}

      - name: Build
        run: npm run build
        env:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
          OPEN_WEATHER_API: ${{ secrets.OPEN_WEATHER_API }}

      # - name: Deploy
      #   run: npm run deploy
